language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: 
  - "14"

install:
  - npm install -D
  - cd ./test/smoke/template
  - npm install -D
  - cd ../../../

scripts:
  - npm test
