language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: 
  - "14"

install:
  - npm install -D
  - cd ./test/smoke/template
  - npm install -D
  - cd ../../../

scripts:
  - npm test
  
# require the branch name to be master (note for PRs this is the base branch name)
notifications:
  email:
    - lsustc@mail.ustc.edu.cn
