language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: 
  - "14"

install:
  - npm install -D
  - cd ./test/smoke/template
  - npm install -D
  - cd ../../../

scripts:
  - npm test

notifications:
  email:
    recipients:
      - lsustc@mail.ustc.edu.cn
    on_success: never # default: change
    on_failure: always # default: always
